// Generated by CoffeeScript 1.5.0
var GlusterFS, gfs;

GlusterFS = require('glusterfs');

gfs = new GlusterFS;

gfs.peer('status', null, function(res) {
  return console.log('Peer Status:', JSON.stringify(res));
});

gfs.volume('info', 'all', function(res) {
  return console.log('Volume Info (All Volumes)', JSON.stringify(res));
});
